server:
  port: 9737

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:discovery-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
