server:
  port: 9742

spring:
  application:
    name: ai-intelligent-service
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:mock-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info
